/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 chair.gltf --transform
Author: Grapxly (https://sketchfab.com/grapxly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-chair-8352824055b04ca29137ad463525d577
Title: Gaming Chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/chair-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.black_skin}
        position={[0, 0.526, 0.045]}
        scale={[0.154, 0.202, 0.255]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.outline}
        position={[0, 0.526, 0.045]}
        scale={[0.154, 0.202, 0.255]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.black_plactic}
        position={[0.033, 0.079, 0.051]}
        rotation={[0, -0.712, 0]}
        scale={[0.02, 0.02, 0.018]}
      />
      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.metal}
        position={[0.245, 0.34, 0.148]}
        scale={[0.012, 0.006, 0.017]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials["Material.002"]}
        position={[-0.005, 0.883, -0.189]}
        rotation={[1.381, 0, 0]}
        scale={[0.118, 0.087, 0.079]}
      />
      <mesh
        geometry={nodes.Object_61.geometry}
        material={materials["Material.001"]}
        position={[0.191, 0.356, -0.113]}
        rotation={[-0.123, 0.177, -1.528]}
        scale={0.013}
      />
    </group>
  );
}

useGLTF.preload("/chair-transformed.glb");
