/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 character.gltf --transform
Author: htbuffalo (https://sketchfab.com/htbuffalo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/archlight-game-model-241ff9d3d8b847a4a0fe885f171e733b
Title: ArchLight Game model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/character-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cone2_Cone_0.geometry} material={materials.Cone} position={[0, -56.78, 0]} rotation={[0, 0.405, 0]} scale={[0.355, 1.606, 0.355]} />
      <mesh geometry={nodes.Body__Body_0.geometry} material={materials.Body} position={[0, -37.577, 0]} rotation={[0.003, 0.403, -0.003]} scale={0.515} />
      <mesh geometry={nodes.Weapon_Weapon_0.geometry} material={materials.Weapon} position={[0, -37.577, 0]} rotation={[0, 0.405, 0]} scale={0.515} />
      <mesh geometry={nodes.Sphere_particle_Sphere_0.geometry} material={materials.Sphere} position={[-38.84, 70.926, 46.361]} rotation={[0, 0.405, 0.249]} scale={0.515} />
      <mesh geometry={nodes.Wings_Wings_0.geometry} material={materials.Wings} position={[0, -37.577, 0]} rotation={[0, 0.405, 0]} scale={0.515} />
    </group>
  )
}

useGLTF.preload('/character-transformed.glb')
