/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 monitor.gltf --transform
Author: Shaurya_Jaiswal (https://sketchfab.com/jaiswalshaurya1310)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultra-wide-monitor-f7445b4b5d84412aa58ed7379483267c
Title: Ultra-Wide Monitor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/monitor.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-0.337, 1.461, 0.088]} rotation={[0, 0, 0.087]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.003']} position={[-0.337, 1.461, 0.088]} rotation={[0, 0, 0.087]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} position={[-0.337, 1.461, 0.088]} rotation={[0, 0, 0.087]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.007']} position={[-0.337, 1.461, 0.088]} rotation={[0, 0, 0.087]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.006']} position={[-0.337, 1.461, 0.088]} rotation={[0, 0, 0.087]} />
    </group>
  )
}

useGLTF.preload('/monitor-transformed.glb')
